theme: jekyll-theme-minimal
title: Airin's homepage
description: Bookmark this to keep an eye on my project updates!

![This is me, Airin H Eddins-Schmist](https://github.com/hekili42/hekili42.github.io/blob/0a3ae8cd61d91e544eebf2915792f6384f26a430/WIN_20250213_22_38_26_Pro.jpg)
